### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by InkDP** [loveinsky100/goanno#27]
java.lang.NullPointerException
	at java.base/java.lang.String.replace(String.java:2143)
	at org.leo.goanno.template.impl.GoMethodTemplateImpl.generateTypeTemplate(GoMethodTemplateImpl.java:135)
	at org.leo.goanno.template.impl.GoMethodTemplateImpl.generateMethodArgs(GoMethodTemplateImpl.java:127)
	at org.leo.goanno.template.impl.GoMethodTemplateImpl.load(GoMethodTemplateImpl.java:64)
	at org.leo.goanno.generate.impl.FuncCommentGeneratorV2Impl.generateTemplate(FuncCommentGeneratorV2Impl.java:110)
	at org.leo.goanno.generate.impl.FuncCommentGeneratorV2Impl.generate(FuncCommentGeneratorV2Impl.java:101)
	at org.leo.goanno.generate.Generator.generateResult(Generator.java:19)
	at org.leo.goanno.utils.GeneratorUtils.generateWithTemplate(GeneratorUtils.java:33)
	at org.leo.goanno.utils.GeneratorUtils.generate(GeneratorUtils.java:18)
	at org.leo.goanno.action.GoAnnoAction.actionPerformed(GoAnnoAction.java:58)
	at com.intellij.openapi.keymap.impl.ActionProcessor.performAction(ActionProcessor.java:65)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$1.performAction(IdeKeyEventDispatcher.java:573)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.lambda$doPerformActionInner$10(IdeKeyEventDispatcher.java:706)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareWithCallbacks(ActionUtil.java:265)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.doPerformActionInner(IdeKeyEventDispatcher.java:702)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:645)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:584)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processActionOrWaitSecondStroke(IdeKeyEventDispatcher.java:467)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.inInitState(IdeKeyEventDispatcher.java:456)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:224)
	at com.intellij.ide.IdeEventQueue.dispatchKeyEvent(IdeEventQueue.java:804)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:754)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:447)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:818)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:446)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:805)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:498)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by loveinsky100** [comment]
有具体需要生成注释的代码没

**Comment by codeconveyer** [comment]
使用的是goland 2022 1.3版本，任意代码均出错

**Comment by loveinsky100** [comment]
邮件已收到。徐

**Comment by loveinsky100** [comment]
https://github.com/loveinsky100/goanno/commit/6e67b5a712d961b662f7af481b27cdc95b68c778
